--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LootSpace369/BroadcastMessage
build-by-default: true
branches:
- main
projects:
 BroadcastMessage:
  path: ""
  libs:
    - src: VennDev/LibVapmPMMP/LibVapmPMMP
      version: 1.8.8
      branch: "main"
...
